### ISSUE TITLE
Can't compile sources

### ISSUE THREAD

**Issue by eugene-griaznov** [concordion/concordion.net#11]
Try to discover functionality. There is a lack of documentation, so I want to see the code and run the tests.
I downloaded the sources and follow the instructions here https://github.com/concordion/concordion.net/blob/master/Concordion/README.md. But the solution does not build:

> Error CS0246  The type or namespace name 'org' could not be found (are you missing a using directive or an assembly reference?)

Could you help me with that? I have no experience with IKVM...

**Comment by ShaKaRee** [comment]
When you copy Concordion.jar and xom.jar into the root directory of the project Concordion and build the project in Visual Studio, you should obtain Concordion.dll in the Concordion\bin\Debug directory.
This is accomplished by a build events:
ikvmc $(ProjectDir)xom.jar -target:library
ikvmc $(ProjectDir)Concordion.jar -target:library -r:$(TargetDir)xom.dll

You could try to simulate this step when you open a command line in the root directory of the Concordion project and type in the following commands:
ikvmc xom.jar -target:library
ikvmc Concordion.jar -target:library -r:bin\Debug\xom.dll

**Comment by eugene-griaznov** [comment]
Concordion.dll building normally by VS and command line. But error still exists.
I tried using [concordion-1.5.1.jar](https://mvnrepository.com/artifact/org.concordion/concordion/1.5.1) and the last [concordion-2.0.3.jar](https://github.com/concordion/concordion/releases/tag/2.0.3).

**Comment by ShaKaRee** [comment]
you need to use this branch of Concordion:
https://github.com/concordion/concordion/tree/IKVM-Base_1.5.1

**Comment by eugene-griaznov** [comment]
And use Java building infrastructure? Too complex circumstances just for build sources. Sorry guys, no contribution from me. :(

**Comment by ShaKaRee** [comment]
Hi Eugene,
I would like to help you and make the build process easier.
Up to now I did not upload the concordion.jar file to the repo of concordion.net, as it would increase the size.
Would it help, if concordion-1.5.1-IKVM-Base would be available on some server for download?

**Comment by eugene-griaznov** [comment]
Yes, it would help.

**Comment by ShaKaRee** [comment]
great, I will take care of it, but it will probably take a weeks time

**Comment by ShaKaRee** [comment]
Hi Eugene,

Happy New Year for you.

Could you try to build Concordion.NET with the attached jar files? Please, copy them into the Concordion project / folder and rebuild the entire solution. I hope it will work for you.

[Concordion_1.5.1-IKVM-Base.zip](https://github.com/concordion/concordion.net/files/695457/Concordion_1.5.1-IKVM-Base.zip)

**Comment by eugene-griaznov** [comment]
Happy New Year for you too! :)

I tried to use attached files but it didn't work: same error.

**Comment by ShaKaRee** [comment]
I hope I understand your situation better.
When I copied the jar files into the Concordion project of the Visual Studio solution, the build within VS did not produce errors. Also the spec tests of Concordion.NET itself could be run. But within the editor of VS the references to the Concordion.dll were still not resolved correctly and the editor shows the error message "The type or namespace 'org'could not be found.
Is this the same situation you experience?

To remove the error message I changed the references. Within the solution instead of pointing to the project Concordion, I copied the Concordion.dll that was generated by the VS build to another location (e.g. packages\Concordion\Concordion.dll) and changed the reference to point to this file. For simplicity I am attaching the current Concordion.dll file that I downloaded from the website concordion.org here.

I hope the attached Concordion.dll helps you to to get the build in your VS up and running. :-)
Additionally, I will upload it to nuget so that it can be used in the Concordion.NET solution.

[Concordion.dll.zip](https://github.com/concordion/concordion.net/files/714206/Concordion.dll.zip)

**Comment by ShaKaRee** [comment]
Hi,

The cross compiled Concordion.dll is now available as nuget package. All dependencies have been changed in the VS solution so that they reference the nuget package.
As a result, you should be able to compile the solution and run all tests. :-)

@eugene-griaznov 
Does it work for you? Are you able to compile the solution without errors?

**Comment by eugene-griaznov** [comment]
Yeah! :smile:
